{{- if .Values.operarius.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openfero.fullname" . }}-operarius-reader
  labels:
    {{- include "openfero.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "openfero.fullname" . }}-operarius-reader
subjects:
- kind: ServiceAccount
  name: {{ include "openfero.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
