{{- if .Values.auth.enabled }}
{{- $createSecret := false }}
{{- if and (eq .Values.auth.method "basic") (not .Values.auth.basic.existingSecret) }}
{{- $createSecret = true }}
{{- end }}
{{- if and (eq .Values.auth.method "bearer") (not .Values.auth.bearer.existingSecret) }}
{{- $createSecret = true }}
{{- end }}

{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openfero.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openfero.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.auth.method "basic" }}
  password: {{ .Values.auth.basic.password | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.auth.method "bearer" }}
  token: {{ .Values.auth.bearer.token | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
